import random

n = 99999
print(bin(n))
print(f"This number {n}, is very large and is stored in the server!")
g = 13
print(f"This number {g}, is very small and is stored in the server!\n")
privatekeya = random.randint(1, n)
print(f"This number {privatekeya}, is a random number (private key) between 1 and {n} and is stored in privately in the device of USER-1.")
privatekeyb = random.randint(1, n)
print(f"This number {privatekeyb}, is a random number (private key) between 1 and {n} and is stored in privately in the device of USER-2.\n")

publickeya = ((g)**privatekeya)%n
print(f"This number {publickeya}, is the public key generated by the USER-1.")
publickeykb = ((g)**privatekeyb)%n
print(f"This number {publickeykb}, is the public key generated by the USER-2.\n")

print("Now they both exchange their public keys.\n")

sharedkeyb = ((publickeya)**privatekeyb)%n
sharedkeya = ((publickeykb)**privatekeya)%n

print("When they both get each others public keys, they combine it with the private keys of themselves to get a common and a near to similar number.\n")

print(f"Common number of USER-1 is {sharedkeya}. Yayy!")
print(f"Common number of USER-2 is {sharedkeyb}. Yayy!\n")

print("Are they same?")
print("Yes.\n") if sharedkeya == sharedkeyb else print("No.\n")

